services:

  code:
    build:
      context: ./code
      dockerfile: Dockerfile
    container_name: code
    volumes:
      - ./code:/home/code
      # be careful. don't use a bin that other things are installing into during
      # build or it will overwrite when mounting. why we don't use /go/bin      
      - ./bin:/usr/local/bin
    working_dir: /home/code
