// Code generated by statch. DO NOT EDIT.

package tutorial

import (
  "github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

Inspect config: map[outputFile:./example0/models.go sources:[map[sourceFile:./example0/schema.sql type:schema] map[sourceFile:queries.sql type:queries]] templateFile:./example0/models.plush]
Template File: ./example0/models.go</li>

Inspect schema: map[statements:[-- I&#39;m a comment
CREATE TABLE author (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
) -- I also deserve a comment
CREATE TABLE book (
  id          BIGSERIAL PRIMARY KEY,
  name        text      NOT NULL,
  description text
)]]
